version: 2
updates:
- package-ecosystem: maven # TODO: lock to 2.3.x?
  directory: /
  schedule:
    interval: weekly
- package-ecosystem: github-actions
  directory: /
  schedule:
    interval: weekly
